"""empty message

Revision ID: ea66683dac80
Revises: 6119c910d957
Create Date: 2023-04-09 18:04:39.328340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea66683dac80'
down_revision = '6119c910d957'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=2),
               existing_nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=12),
               existing_nullable=True)

    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=2),
               existing_nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=12),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.String(length=12),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.alter_column('state',
               existing_type=sa.String(length=2),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.String(length=12),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.alter_column('state',
               existing_type=sa.String(length=2),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###
